### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by SirawichDev** [pangpondxd/ReactBlog#1]
got it when i try to run  npm start => TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined 

 might be from react-scripts 👀 eieii

**Comment by SirawichDev** [comment]
fixed it's really from version of react-script need to upgrade version and work fine

**Comment by pangpondxd** [comment]
TATATATATATATAT TEPPPPPPP lnw
